name: CI/CD

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io
      if: runner.os == 'Linux'

    - name: Start Docker Compose
      run: docker-compose up -d

    - name: Install Python Requirements
      run: make install-requirements

    - name: Run Node.js Server
      run: make run-server
