name: Docker Compose Task

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
          
      - name: Clone CA4 Repository
        run: git clone https://github.com/FahadKamran2001/CA4.git
          
      - name: Docker Network Creation
        run: docker network create app-db-network
        
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Docker Containers
        run: docker-compose build

      - name: Run Docker Containers
        run: docker-compose up -d
        
